### ISSUE TITLE
Some examples of Artificial Neural Network was not found

### ISSUE THREAD

**Issue by cpy18727** [Girrajjangid/MachineLearning_Algorithms#2]
Some examples of Artificial Neural Network was not found
like :
Demo | Multivariate Classification with Artificial Neural Network using Sigmoid function

please add them, thanks so much !!!

**Comment by Girrajjangid** [comment]
@cpy18727 
Thank you for commenting on this. But my friend the example which you want already there.
link ===>  https://github.com/Girrajjangid/Machine-Learning-from-Scratch/blob/master/Artificial%20Neural%20Network/MultiClass%20Classification%20Neural%20Network_1(%20with%20sigmoid%20).ipynb

#HappyLearning
