### ISSUE TITLE
implement svd in linear from scratch

### ISSUE THREAD

**Issue by neganasiri93** [Girrajjangid/MachineLearning_Algorithms#4]
hi ,can you help me? i want  to implement SVD inLinear regression from scratch?

**Comment by Girrajjangid** [comment]
Hi @neganasiri93 , Thank you for raising an issue. You can find your solution here-
https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/
You can reduce the dimension of your data using the above thread. Then implement it on Linear Regression model.
